# Generated by Django 5.2 on 2025-10-02 13:57

import django.db.models.deletion
import django.utils.timezone
import patrimonio.utils.photo
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EsquecimentoCRACHA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50)),
                ('colaborador', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('data', models.DateField(auto_now_add=True)),
                ('motivo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('VISITANTE', 'Visitante'), ('FORNECEDOR', 'Fornecedores/Prestadores de Serviços')], max_length=50)),
                ('subcategoria', models.CharField(blank=True, choices=[('CLT', 'Trabalhador CLT'), ('PJ', 'Pessoa Jurídica (PJ)'), ('MEI', 'Microempreendedor Individual (MEI)'), ('AUTONOMO', 'Autônomo'), ('ASSOCIADO', 'Associado')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('Integrado', 'Integrado'), ('Pendente', 'Pendente')], default='Integrado', max_length=20)),
                ('validade_meses', models.IntegerField()),
                ('data_integracao', models.DateField(blank=True, null=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='photos/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['-created_at'],
            },
            bases=(models.Model, patrimonio.utils.photo.Base64ImageMixin),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Ação')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Registro de Atividade',
                'verbose_name_plural': 'Registros de Atividades',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ControleChaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=100)),
                ('matricula_recebendo', models.CharField(max_length=50)),
                ('colaborador_recebendo', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('foto_entrega', models.ImageField(upload_to='entregas/')),
                ('data_saida', models.DateTimeField(auto_now_add=True)),
                ('matricula_devolveu', models.CharField(blank=True, max_length=50, null=True)),
                ('colaborador_devolveu', models.CharField(blank=True, max_length=100, null=True)),
                ('foto_devolucao', models.ImageField(blank=True, null=True, upload_to='devolucoes/')),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
                ('situacao', models.CharField(default='RETIRADO', max_length=100)),
                ('chave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimonio.chave')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entrega', models.CharField(max_length=255)),
                ('descricao_item', models.TextField()),
                ('nome_transportadora', models.CharField(max_length=255)),
                ('nome_entregador', models.CharField(max_length=255)),
                ('documentos_entregador', models.CharField(max_length=255)),
                ('data_hora_recebimento', models.DateTimeField()),
                ('nome_matricula_responsavel', models.CharField(max_length=255)),
                ('assinatura_responsavel', models.TextField(help_text='Pode armazenar assinatura digital, base64 ou texto')),
                ('data_hora_entrega_material', models.DateTimeField()),
                ('foto_caixa_entrega', models.ImageField(blank=True, null=True, upload_to='fotos_entregas/')),
                ('fornecedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='patrimonio.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='EntradaFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('horario_entrada', models.TimeField(auto_now_add=True)),
                ('horario_saida', models.TimeField(blank=True, null=True)),
                ('base', models.CharField(max_length=100)),
                ('assinatura_portaria', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Em andamento', 'Em andamento'), ('Saiu', 'Saiu')], default='Em andamento', max_length=20)),
                ('setor_destino', models.CharField(max_length=255)),
                ('responsavel_autorizante', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo_veiculo', models.CharField(blank=True, max_length=100, null=True)),
                ('placa_veiculo', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='patrimonio.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Autonomo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_representante', models.CharField(max_length=255)),
                ('documento_identificacao', models.FileField(help_text='Documento de identificação com foto (CPF, RG ou CNH)', upload_to='documentos/identificacao/')),
                ('foto_representante', models.ImageField(blank=True, help_text='Captura de Foto do Representante', null=True, upload_to='documentos/fotos_representantes/')),
                ('carteira_orgao_profissional', models.FileField(blank=True, help_text='Carteira do órgão profissional (quando aplicável)', null=True, upload_to='documentos/carteiras_profissionais/')),
                ('declaracao_autonomo', models.FileField(help_text='Declaração de autônomo - registro na Prefeitura Municipal', upload_to='documentos/autonomo/declaracoes/')),
                ('contrato_prestacao_servico', models.FileField(help_text='Contrato de prestação de serviço com a assessoria contratante', upload_to='documentos/autonomo/contratos/')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autonomos', to='patrimonio.fornecedor')),
            ],
            options={
                'verbose_name': 'Autônomo',
                'verbose_name_plural': 'Autônomos',
            },
        ),
        migrations.CreateModel(
            name='Associado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_representante', models.CharField(max_length=255)),
                ('documento_identificacao', models.FileField(help_text='Documento de identificação com foto (CPF, RG ou CNH)', upload_to='documentos/identificacao/')),
                ('foto_representante', models.ImageField(blank=True, help_text='Captura de Foto do Representante', null=True, upload_to='documentos/fotos_representantes/')),
                ('carteira_orgao_profissional', models.FileField(blank=True, help_text='Carteira do órgão profissional (quando aplicável)', null=True, upload_to='documentos/carteiras_profissionais/')),
                ('contrato_associacao', models.FileField(help_text='Contrato de associação', upload_to='documentos/associado/contratos/')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associados', to='patrimonio.fornecedor')),
            ],
            options={
                'verbose_name': 'Associado',
                'verbose_name_plural': 'Associados',
            },
        ),
        migrations.CreateModel(
            name='FornecedorServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=255)),
                ('atividade_servico', models.CharField(max_length=255)),
                ('fornecedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor_servico', to='patrimonio.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='MEI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_representante', models.CharField(max_length=255)),
                ('documento_identificacao', models.FileField(help_text='Documento de identificação com foto (CPF, RG ou CNH)', upload_to='documentos/identificacao/')),
                ('foto_representante', models.ImageField(blank=True, help_text='Captura de Foto do Representante', null=True, upload_to='documentos/fotos_representantes/')),
                ('carteira_orgao_profissional', models.FileField(blank=True, help_text='Carteira do órgão profissional (quando aplicável)', null=True, upload_to='documentos/carteiras_profissionais/')),
                ('certificado_mei', models.FileField(help_text='Certificado da condição de Microempreendedor Individual', upload_to='documentos/mei/certificados/')),
                ('contrato_prestacao_servico', models.FileField(help_text='Contrato de prestação de serviço com a assessoria contratante', upload_to='documentos/mei/contratos/')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meis', to='patrimonio.fornecedor')),
            ],
            options={
                'verbose_name': 'Microempreendedor Individual (MEI)',
                'verbose_name_plural': 'Microempreendedores Individuais (MEI)',
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=100)),
                ('data', models.DateField(auto_now_add=True)),
                ('ocorrencia', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_representante', models.CharField(max_length=255)),
                ('documento_identificacao', models.FileField(help_text='Documento de identificação com foto (CPF, RG ou CNH)', upload_to='documentos/identificacao/')),
                ('foto_representante', models.ImageField(blank=True, help_text='Captura de Foto do Representante', null=True, upload_to='documentos/fotos_representantes/')),
                ('carteira_orgao_profissional', models.FileField(blank=True, help_text='Carteira do órgão profissional (quando aplicável)', null=True, upload_to='documentos/carteiras_profissionais/')),
                ('cnpj', models.FileField(help_text='Cadastro Nacional de Pessoa Jurídica (CNPJ)', upload_to='documentos/pj/cnpj/')),
                ('contrato_prestacao_servico', models.FileField(help_text='Contrato de prestação de serviço com a assessoria contratante', upload_to='documentos/pj/contratos/')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas_juridicas', to='patrimonio.fornecedor')),
            ],
            options={
                'verbose_name': 'Pessoa Jurídica (PJ)',
                'verbose_name_plural': 'Pessoas Jurídicas (PJ)',
            },
        ),
        migrations.CreateModel(
            name='TrabalhadorCLT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_representante', models.CharField(max_length=255)),
                ('documento_identificacao', models.FileField(help_text='Documento de identificação com foto (CPF, RG ou CNH)', upload_to='documentos/identificacao/')),
                ('foto_representante', models.ImageField(blank=True, help_text='Captura de Foto do Representante', null=True, upload_to='documentos/fotos_representantes/')),
                ('carteira_orgao_profissional', models.FileField(blank=True, help_text='Carteira do órgão profissional (quando aplicável)', null=True, upload_to='documentos/carteiras_profissionais/')),
                ('descricao_cargo', models.CharField(max_length=255)),
                ('aso', models.FileField(help_text='Atestado de saúde ocupacional – ASO mais recente', upload_to='documentos/clt/aso/')),
                ('ordem_servico', models.FileField(help_text='Ordem de Serviço, por função', upload_to='documentos/clt/ordem_servico/')),
                ('pgr', models.FileField(help_text='Programa de Gerenciamento de Riscos – PGR', upload_to='documentos/clt/pgr/')),
                ('pcmso', models.FileField(help_text='Programa de Controle Médico de Saúde Ocupacional – PCMSO', upload_to='documentos/clt/pcmso/')),
                ('certificados_treinamentos', models.FileField(help_text='Certificados e treinamentos conforme o risco e atividade', upload_to='documentos/clt/certificados/')),
                ('cautela_epi_epc', models.FileField(help_text='Cautela de EPI e EPC', upload_to='documentos/clt/cautela_epi/')),
                ('apr_pt', models.FileField(help_text='Análise Preliminar de Risco - APR ou Permissão de trabalho – PT', upload_to='documentos/clt/apr_pt/')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabalhadores_clt', to='patrimonio.fornecedor')),
            ],
            options={
                'verbose_name': 'Trabalhador CLT',
                'verbose_name_plural': 'Trabalhadores CLT',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, verbose_name='É Administrador')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Usuário Bloqueado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('documento', models.CharField(help_text='RG, CPF ou CNH', max_length=100)),
                ('motivo_visita', models.CharField(max_length=255)),
                ('foto_visitante', models.ImageField(blank=True, null=True, upload_to='fotos_visitantes/')),
                ('fornecedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visitante', to='patrimonio.fornecedor')),
            ],
            bases=(models.Model, patrimonio.utils.photo.Base64ImageMixin),
        ),
    ]
