# Generated by Django 5.2 on 2025-10-07 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='data_integracao',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='data_validade',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='validade_meses',
        ),
        migrations.CreateModel(
            name='Integracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_integracao', models.DateField()),
                ('validade_meses', models.PositiveIntegerField()),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integracoes', to='patrimonio.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionarioIntegracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questao1', models.BooleanField()),
                ('questao2', models.BooleanField()),
                ('questao3', models.BooleanField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('integracao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionario', to='patrimonio.integracao')),
            ],
        ),
    ]
