# Generated by Django 5.2 on 2025-04-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleChaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=50)),
                ('colaborador', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('situacao', models.CharField(default='RETIRADO', max_length=100)),
            ],
        ),
    ]
