# Generated by Django 5.2 on 2025-10-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0002_remove_fornecedor_data_integracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='status',
            field=models.CharField(choices=[('Sem integração', 'Sem integração'), ('Integrado', 'Integrado'), ('Pendente', 'Pendente')], default='Sem integração', max_length=20),
        ),
    ]
