# Generated by Django 5.2 on 2025-04-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0003_alter_controlechaves_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlechaves',
            name='situacao',
            field=models.CharField(default='RETIRADO', max_length=100),
        ),
    ]
