# Generated by Django 5.2 on 2025-10-09 13:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0004_integracaotoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integracaotoken',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='integracaotoken',
            name='fornecedor',
        ),
        migrations.AddField(
            model_name='integracao',
            name='uuid_link',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='integracaotoken',
            name='integracao',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='patrimonio.integracao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='integracaotoken',
            name='token',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
