# Generated by Django 5.2 on 2025-04-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0004_alter_controlechaves_situacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
            ],
        ),
    ]
