# Generated by Django 5.2 on 2025-05-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0005_colaborador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18)),
                ('nome', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Integrado', 'Integrado'), ('Pendente', 'Pendente')], default='Integrado', max_length=20)),
                ('validade_meses', models.IntegerField(help_text='Validade em meses')),
                ('data_integracao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
