# Generated by Django 5.2 on 2025-10-09 14:53

import django.db.models.deletion
import patrimonio.models.fornecedor
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0005_remove_integracaotoken_criado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='integracaotoken',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='integracaotoken',
            name='uuid_link',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='integracaotoken',
            name='expira_em',
            field=models.DateTimeField(default=patrimonio.models.fornecedor.default_expira_em),
        ),
        migrations.AlterField(
            model_name='integracaotoken',
            name='integracao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='patrimonio.integracao'),
        ),
        migrations.AlterField(
            model_name='integracaotoken',
            name='token',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
