# Generated by Django 5.2 on 2025-10-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0006_integracaotoken_criado_por_integracaotoken_uuid_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integracao',
            name='data_integracao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
