# Generated by Django 5.2 on 2025-05-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0007_alter_fornecedor_validade_meses'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='data_validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='validade_meses',
            field=models.IntegerField(help_text='Validade em meses'),
        ),
    ]
