# Generated by Django 5.2 on 2025-05-15 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0008_fornecedor_data_validade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='data_integracao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='validade_meses',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='EntradaFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('horario_entrada', models.TimeField(auto_now_add=True)),
                ('horario_saida', models.TimeField(blank=True, null=True)),
                ('base', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('visitantes', models.TextField()),
                ('tipo_documento', models.TextField()),
                ('documento', models.TextField()),
                ('setor', models.CharField(max_length=100)),
                ('responsavel', models.CharField(max_length=100)),
                ('assinatura_portaria', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Em andamento', 'Em andamento'), ('Saiu', 'Saiu')], default='Em andamento', max_length=20)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='patrimonio.fornecedor')),
            ],
        ),
    ]
