# Generated by Django 5.2 on 2025-05-19 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0009_alter_fornecedor_data_integracao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornecedor',
            old_name='cnpj',
            new_name='cpf',
        ),
    ]
