# Generated by Django 5.2 on 2025-05-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0010_rename_cnpj_fornecedor_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaFornecedorAvulso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('horario_entrada', models.TimeField(auto_now_add=True)),
                ('horario_saida', models.TimeField(blank=True, null=True)),
                ('base', models.CharField(max_length=100)),
                ('fornecedor_nome', models.CharField(max_length=100)),
                ('cpf_ou_cnpj', models.CharField(max_length=20)),
                ('quantidade', models.IntegerField()),
                ('visitantes', models.TextField()),
                ('tipo_documento', models.TextField()),
                ('documento', models.TextField()),
                ('setor', models.CharField(max_length=100)),
                ('responsavel', models.CharField(max_length=100)),
                ('assinatura_portaria', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Em andamento', 'Em andamento'), ('Saiu', 'Saiu')], default='Em andamento', max_length=20)),
            ],
        ),
    ]
