# Generated by Django 5.2 on 2025-05-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0011_entradafornecedoravulso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='data_integracao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='validade_meses',
            field=models.IntegerField(help_text='Validade em meses'),
        ),
    ]
