# Generated by Django 5.2 on 2025-06-04 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0012_alter_fornecedor_data_integracao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='controlechaves',
            name='chave',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patrimonio.chave'),
            preserve_default=False,
        ),
    ]
