# Generated by Django 5.2 on 2025-06-16 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0013_chave_controlechaves_chave'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsquecimentoCRACHA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50)),
                ('colaborador', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('data', models.DateField(auto_now_add=True)),
                ('motivo', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='tipo',
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
