# Generated by Django 5.2 on 2025-06-16 18:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0014_esquecimentocracha_remove_ocorrencia_tipo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlechaves',
            old_name='colaborador',
            new_name='colaborador_entregou',
        ),
        migrations.RenameField(
            model_name='controlechaves',
            old_name='matricula',
            new_name='matricula_entregou',
        ),
        migrations.AddField(
            model_name='controlechaves',
            name='colaborador_recebeu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='controlechaves',
            name='data_hora_devolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlechaves',
            name='data_hora_saida',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controlechaves',
            name='foto_devolucao',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_chaves/'),
        ),
        migrations.AddField(
            model_name='controlechaves',
            name='foto_entrega',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_chaves/'),
        ),
        migrations.AddField(
            model_name='controlechaves',
            name='matricula_recebeu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
