# Generated by Django 5.2 on 2025-06-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0015_rename_colaborador_controlechaves_colaborador_entregou_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlechaves',
            old_name='data_hora_saida',
            new_name='data_saida',
        ),
        migrations.RemoveField(
            model_name='controlechaves',
            name='data_hora_devolucao',
        ),
        migrations.AddField(
            model_name='controlechaves',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='controlechaves',
            name='foto_devolucao',
            field=models.ImageField(blank=True, null=True, upload_to='devolucoes/'),
        ),
        migrations.AlterField(
            model_name='controlechaves',
            name='foto_entrega',
            field=models.ImageField(blank=True, null=True, upload_to='entregas/'),
        ),
    ]
