# Generated by Django 5.2 on 2025-06-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0016_rename_data_hora_saida_controlechaves_data_saida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlechaves',
            name='colaborador_recebeu',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='controlechaves',
            name='data_devolucao',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='controlechaves',
            name='foto_devolucao',
            field=models.ImageField(upload_to='devolucoes/'),
        ),
        migrations.AlterField(
            model_name='controlechaves',
            name='matricula_recebeu',
            field=models.CharField(max_length=50),
        ),
    ]
