# Generated by Django 5.2 on 2025-06-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0017_alter_controlechaves_colaborador_recebeu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlechaves',
            name='data_devolucao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
