# Generated by Django 5.2 on 2025-06-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0018_alter_controlechaves_data_devolucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlechaves',
            name='colaborador_recebeu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='controlechaves',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='controlechaves',
            name='foto_devolucao',
            field=models.ImageField(blank=True, null=True, upload_to='devolucoes/'),
        ),
        migrations.AlterField(
            model_name='controlechaves',
            name='matricula_recebeu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
