# Generated by Django 5.2 on 2025-06-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0019_alter_controlechaves_colaborador_recebeu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlechaves',
            name='foto_entrega',
            field=models.ImageField(default=1, upload_to='entregas/'),
            preserve_default=False,
        ),
    ]
