# Generated by Django 5.2 on 2025-06-17 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0020_alter_controlechaves_foto_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entrega', models.CharField(max_length=255)),
                ('descricao_item', models.TextField()),
                ('quantidade_recebida', models.PositiveIntegerField()),
                ('nome_transportadora', models.CharField(max_length=255)),
                ('nome_entregador', models.CharField(max_length=255)),
                ('documentos_entregador', models.CharField(max_length=255)),
                ('placa_veiculo', models.CharField(max_length=20)),
                ('data_hora_recebimento', models.DateTimeField()),
                ('setor_destino', models.CharField(max_length=255)),
                ('nome_matricula_responsavel', models.CharField(max_length=255)),
                ('assinatura_responsavel', models.TextField(help_text='Pode armazenar assinatura digital, base64 ou texto')),
                ('data_hora_entrega_material', models.DateTimeField()),
                ('imagem_material', models.ImageField(blank=True, null=True, upload_to='imagens_entregas/')),
            ],
        ),
        migrations.CreateModel(
            name='FornecedorServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=255)),
                ('nome_representante', models.CharField(max_length=255)),
                ('documento', models.CharField(help_text='RG, CPF ou CNH', max_length=100)),
                ('setor_destino', models.CharField(max_length=255)),
                ('atividade_servico', models.CharField(max_length=255)),
                ('responsavel_autorizante', models.CharField(max_length=255)),
                ('modelo_veiculo', models.CharField(blank=True, max_length=100, null=True)),
                ('placa_veiculo', models.CharField(blank=True, max_length=20, null=True)),
                ('data_hora_entrada', models.DateTimeField()),
                ('data_hora_saida', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('documento', models.CharField(help_text='RG, CPF ou CNH', max_length=100)),
                ('motivo_visita', models.CharField(max_length=255)),
                ('setor_destino', models.CharField(max_length=255)),
                ('responsavel_autorizante', models.CharField(max_length=255)),
                ('modelo_veiculo', models.CharField(blank=True, max_length=100, null=True)),
                ('placa_veiculo', models.CharField(blank=True, max_length=20, null=True)),
                ('data_hora_entrada', models.DateTimeField()),
                ('data_hora_saida', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EntradaFornecedorAvulso',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='cpf',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='categoria',
            field=models.CharField(choices=[('VISITANTE', 'Visitante'), ('FORNECEDOR', 'Fornecedores/Prestadores de Serviços'), ('ENTREGA', 'Entregas')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='entrega',
            name='fornecedor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='patrimonio.fornecedor'),
        ),
        migrations.AddField(
            model_name='fornecedorservico',
            name='fornecedor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor_servico', to='patrimonio.fornecedor'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='fornecedor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visitante', to='patrimonio.fornecedor'),
        ),
    ]
