# Generated by Django 5.2 on 2025-06-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0021_entrega_fornecedorservico_visitante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='nome',
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='validade_meses',
            field=models.IntegerField(max_length=20),
        ),
    ]
