# Generated by Django 5.2 on 2025-06-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0022_remove_fornecedor_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='imagem_material',
            field=models.ImageField(upload_to='imagens_entregas/'),
        ),
    ]
