# Generated by Django 5.2 on 2025-06-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0024_alter_entrega_imagem_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='imagem_material',
            field=models.ImageField(upload_to='imagens_entregas/'),
        ),
    ]
