# Generated by Django 5.2 on 2025-06-17 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0025_alter_entrega_imagem_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedorservico',
            name='data_hora_entrada',
        ),
        migrations.RemoveField(
            model_name='fornecedorservico',
            name='data_hora_saida',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='data_hora_entrada',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='data_hora_saida',
        ),
    ]
