# Generated by Django 5.2 on 2025-07-11 18:36

import django.utils.timezone
import patrimonio.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0028_remove_entrega_placa_veiculo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='photos/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['-created_at'],
            },
            bases=(models.Model, patrimonio.utils.Base64ImageMixin),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='validade_meses',
            field=models.IntegerField(),
        ),
    ]
