# Generated by Django 5.2 on 2025-07-11 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0029_photo_alter_fornecedor_validade_meses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='imagem_material',
        ),
    ]
