# Generated by Django 5.2 on 2025-07-14 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0031_rename_colaborador_entregou_controlechaves_colaborador_recebendo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlechaves',
            old_name='colaborador_recebeu',
            new_name='colaborador_devolveu',
        ),
        migrations.RenameField(
            model_name='controlechaves',
            old_name='matricula_recebeu',
            new_name='matricula_devolveu',
        ),
    ]
