# Generated by Django 5.2 on 2025-08-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0032_rename_colaborador_recebeu_controlechaves_colaborador_devolveu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='categoria',
            field=models.CharField(choices=[('VISITANTE', 'Visitante'), ('FORNECEDOR', 'Fornecedores/Prestadores de Serviços')], max_length=50),
        ),
    ]
